# Telegram Bot
telegram_token = "8294983391:AAGanrcBHuR1LXk5yn13aSzF6DMWWaILm9I"
telegram_chat_id = "-1002915032638"

# Email credentials
email_sender = "signalvyapar@outlook.com"
email_password = "YOUR_EMAIL_APP_PASSWORD"
email_receiver = "shivamozarkar3131@gmail.com"

{
  "type": "service_account",
  "project_id": "shaped-glazing-474707-t5",
  "private_key_id": "fed2a0714758769874ac528df5e08f061cb381e0",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDYQVOQvnNqahGO\nw0nIoDvle5ilUKH6TVzgf9oGFF05G9nv510cCB43BymrbzAcTOVkmMJrRzh2rx3x\nc9SCJ/t8RMSsJt1Vb4R84iPiYbPQWg/yGnKg6OAyxnOVgggDIEJcaLqlr05+bBIL\nWIHHSYVX/sr9i+foA+JsrXPStesk+GT5n+smhBr2G8sUSexzw/JT7ptP+GdOK2Fh\nwPSq8M5Z6KKsETPK4TC+h8jg/mnVxzw0LHJ5gjsmxb8xrUc9zukroCaQLrY73jGA\n9Vwhi1Tbwgbfa8VI9L+e3UIhFVRlntT+JQYRsk3kGHxmvBDugUuGT1cUNdH4t6j4\nUqHcMsklAgMBAAECggEAJLkLMMQ2ozZ53s1o5SnYogKYDFKh/vhOMk1jv66LmhwR\nqTyXwh/ayatstxD9kYC5X5jVQxRoETdxlUP/LU8O1K5022sKIOz8CZz5TQMcXuA8\nXveAybRiBh1PGW9oXueGfVzHfUVExhEiC00vVKE2hJfe7qloayzlsWDPD1QXJ0K7\nLVEzQlOqjODpCfk6dbBCgORxnmKI/EjG9QZqXnPo6AUpxBUtEG/lUEyaQ1rJb4jJ\nOWNZt80FX2IQWmkhYQULtRE/GwzVraStL4VH9Jyq4iTrOpkXYn4gnwM11shA2EgH\n1fWaJ7sfe3xypoYcUvqdW1cfuhxx1Fci43zZ3JP0wQKBgQDwI2Fr1eDDbC80BYif\nkQ1U42RUkobuJJwQIvcNJQwjUqmXDOHTRVEfkArI6/VoyDDasREB7jY+RtQm3fpO\nzR4/CmHJCbkpcksDsadTvXQRdpml07hIp/kIlg/XWfEaEh2qMuOlzqh+m4/Ayh2A\nu5V7wOWO4cW5xd48mn1/qGs59QKBgQDmihh7sP/LL2WcThN63tURBqig5H+uO/2c\nbGsCEkwDG7ehwar39YrIPBW/5RfMwovxcAwpyJUt4oKQ1w7TfnWHvOH7P+73QdOF\nrTQku6v9McYOSsp3mctn+FArW+BmklQaBmivefaHPz4VyLi4nPF2bbzj4x6kc+El\npBzTaEDkcQJ/Qalq+hGBY+4w+giJUxhWjN+gj3+BZZydD8x/wRhgOUhhFuxu01Yg\n2ICKcmYStJQIx8Oi4uQ/8MdtOzN3PhTYMGSmWFJQTwTxfhEVr9Ad7KiBWtaJjVRg\nw/hEXJ47TuWlNuSzWqMnb3cZ151sc8bXGP+lxWv2pNV17xxPNJjYuQKBgHlMG4mp\nHU0YyQuugM1bRRvKNxtAXnWcFtogqUTTv666/KldLsl8JeMoygDHVvhjPCJyY9Pw\nN52G2k++94wLs2cR2IzLnL33ooVpFlBldh6n+581dsXq43z2x6eola8iOqHe0WHS\neAW9Hrtzes2Xtewr3QDCVTMNzV5ytL/+0HXhAoGAQ1x/aUHXGKj+XdZgcOqTEuKQ\nhb5bGmj+EL03GuOtlqwWmcSPjWkQDBIJcCvVzrehrNtFrlFBIq+OV778/6OYgmHY\nkDugrMtizGHNKHlMiS2jgzv4hSUNX0VK71dxe+9hWbsUoHJy9KfxgFRAKhGP1ptN\nwGPtFmYKKN4bITlDoeo=\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-watchlist@shaped-glazing-474707-t5.iam.gserviceaccount.com",
  "client_id": "105896561820418370117",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-watchlist%40shaped-glazing-474707-t5.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}



