# Telegram Bot
telegram_token = "8294983391:AAGanrcBHuR1LXk5yn13aSzF6DMWWaILm9I"
telegram_chat_id = "6794383773"

# Email credentials
email_sender = "signalvyapar@outlook.com"
email_password = "YOUR_EMAIL_APP_PASSWORD"
email_receiver = "shivamozarkar3131@gmail.com"

# Google Sheets
g_sheet_json = '''
{
  "type": "service_account",
  "project_id": "stunning-strand-469318-d4",
  "private_key_id": "53ea931e1dbf14cdb89733fe0b3458f9fca9baf8",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsJywD4EwWENqn\nrcXjt8xsRMiZbTlJKND8HwFeUdXh02mYXnO8mK87A1FIf7bRfD7O2Y7KDApENvY7\n9KAmsH5PYGRpTFsrtPEPUcvp+vuB9FJWFPxPMRWBQfy/YnGNqgWfg7uGYIx+zmpj\nNHQeT9HIC0wnmb292JVcepGpq8muS9uSu+iVohzFI1u8KgJlewZ6TNK+y6w+U90m\nlM9mykZ5Y9zx+AqJQDp80Xgt0usGfUsYYjqLVRi1ixI1L+fXEu2RUt4jLHpzT3/K\nr4SggjQ7h1HRDcoaLdZI0TgpXKMg7uDzEXB4+yU/IAJ0vFEsRlQseo0EucP8UurB\nbWRaJ5qNAgMBAAECggEAAIepE2S3M9/exorwqNiG43XMo3AOefs6ck0TZTaQOTGT\nxmzFRRDFkih1qrMYri5munZGxT8UxJaRChsnqtbSPmZOxXOTZ22DG5v25uJ7lRUW\n31+YN3HEqBK6t3HJBvY9maoM1GkC788YpKKxEXH5+0kvuOD1Rk05sHn6AcIRdXE0\nFmbiMp+dDD6TarDZ76LvaXTd0wsW70JAxswp+lcFmmbKi9o65HI7tG/iEzVCVbVD\np1gpHXpL6HsIJtxbt55DAMidDFBVBbcmNJJiV9Ck3E2UnL97NEAc2igQox/V41Wm\ndtvqELCQ5bCpvrtQLC4eI1YkFZuJrshy+jaVeu4uQQKBgQDsKkhrTMCR8tEukJ6z\nTJuLjRj17U9dyyFSGK8g2TxuJD8DFUWD9EosOqyPm/KOLRjotpIZ7tKFhtrfU4jZ\nTpsU1KaGb5/ZOmxbH5/YxjCYhY2LY0ZFC+65xw9YuQ2ZZJLm1JdtmWLhuzwsTpC6\nfyvn3t1hNIMFMoXZlHsEL2AW0QKBgQC6nJUw+E59k9EroSb/qvgQTX35ptmjS/Rz\nrlTnBIEpJMGaVLuZSu8NNRvo/QxsDULdb3keu5QeQGWHPOf57OC3r5oOQnYpvoN4\nG2LMIENCe2B4NBbKp9vM4yxUAukaaty7sYgiCCLF1A9MQ68EHhMj3MnJOAPRanXP\nwCu8N3+u/QKBgQCID/xVRY0VCS6Xg17LsnFTP2GIHsdBJIz3/Zy4cjAszNk474Jz\necVaIhvVSWW/oB/fw3/9TOkhYQas8DXB7VXP9IxUm+8eelh/T4MKo3TQCvH3wqRz\nl2JcymD/Hu7E13sDXqw3ys17fCI47LLZn/ctyesF2/k4f1k6eB8/1AOqYQKBgF6P\nY8YZvORDV/XMxk89mk/ghJpR4uytW2SXDSy3CqAHoRcMIret0e6WX9szBu1l1uEQ\nUIazNH4T0Z6yzTXGw6QwllbtdKT4hfQBpJGdM5fnnt2qP3ZXkriC0P6NLwOU7N8r\nOblM+BnYuBvEHFZwyvAcPB/7g2vFj4dDcKYCVXAdAoGAJ3FO0GPYm3TTJS2+eUpq\nJ9L5M4e33peJMDUW3KzFULpz300dhahgFYJRR1ZC1SGOWf9MbVm+2BoCg5OTo5Hv\nVpNt8OJgMxsJdbFC+V69VFfXUN5MiRpVS0kyYlHEiVqgLJOSx5sYoDmq1K2OpvJG\ng75hGcqHwTp/vKh9PhJE+EA=\n-----END PRIVATE KEY-----\n",
  "client_email": "sv-734@stunning-strand-469318-d4.iam.gserviceaccount.com",
  "client_id": "115505209422807651400",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sv-734%40stunning-strand-469318-d4.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''

g_sheet_id = "1AAXg5Ns8mlnE3TsLaq8N7M6k0nq03SC0vbEEMIN9jl4"
g_sheet_tab = "Sheet1"
