# Telegram Bot
telegram_token = "8294983391:AAGanrcBHuR1LXk5yn13aSzF6DMWWaILm9I"
telegram_chat_id = "-1002915032638"

# Email credentials
email_sender = "signalvyapar@outlook.com"
email_password = "YOUR_EMAIL_APP_PASSWORD"
email_receiver = "shivamozarkar3131@gmail.com"

